# Generated by Django 3.1.7 on 2021-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='friendly_name',
        ),
    ]
