# Generated by Django 3.1.7 on 2021-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_cuisine_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
