# Generated by Django 3.1.7 on 2021-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20210318_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_1',
            field=models.CharField(default='Please enter address', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_2',
            field=models.CharField(default='Please enter address', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='county',
            field=models.CharField(default='Please enter county', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='post_code',
            field=models.CharField(default='Please enter post code', max_length=254),
        ),
    ]
