# Generated by Django 3.1.7 on 2021-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210318_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='friendly_name',
            field=models.CharField(default='Please enter the name to be displayed on the website', max_length=254),
            preserve_default=False,
        ),
    ]
