# Generated by Django 3.1.7 on 2021-03-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menusection_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='friendly_name',
            field=models.CharField(default='Please set friendly name', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4),
        ),
    ]
