# Generated by Django 3.1.7 on 2021-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20210318_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='friendly_name',
            field=models.CharField(default='Please set friendly name', max_length=254),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='friendly_name',
            field=models.CharField(default='Please set friendly name', max_length=254),
        ),
    ]
