# Generated by Django 3.1.7 on 2021-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20210319_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='icon_html',
            field=models.TextField(default='Please enter icon html', max_length=254),
        ),
    ]
