# Generated by Django 3.1.7 on 2021-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20210401_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=254),
        ),
    ]
