# Generated by Django 3.1.7 on 2021-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20210401_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
