# Generated by Django 3.1.7 on 2021-05-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20210504_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusection',
            options={'verbose_name_plural': 'Menu Sections'},
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='restaurants.restaurant'),
        ),
    ]
