# Generated by Django 3.1.7 on 2021-05-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_auto_20210504_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
    ]
