# Generated by Django 3.1.7 on 2021-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customerprofile_default_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(default='Full name', max_length=254),
        ),
    ]
