# Generated by Django 3.1.7 on 2021-04-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210419_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='name',
            new_name='full_name',
        ),
    ]
