# Generated by Django 3.1.7 on 2021-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210420_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='default_city',
            field=models.CharField(default='Dublin', max_length=6),
        ),
    ]
