# Generated by Django 3.1.7 on 2021-03-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address2',
        ),
    ]
