# Generated by Django 3.1.7 on 2021-03-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210326_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='address_2',
        ),
    ]
