# Generated by Django 3.1.7 on 2021-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210326_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dublin', max_length=6),
        ),
    ]
