# Generated by Django 3.1.7 on 2021-04-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_phone_number'),
        ('checkout', '0009_auto_20210427_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_restaurant',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.restaurant'),
        ),
    ]
