# Generated by Django 3.1.7 on 2021-04-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_phone_number'),
        ('checkout', '0010_auto_20210427_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_restaurant',
            field=models.ForeignKey(default=1, max_length=128, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
