# Generated by Django 3.1.7 on 2021-04-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20210428_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
