# Generated by Django 3.1.7 on 2021-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='additional_details',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
