# Generated by Django 3.1.7 on 2021-05-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_auto_20210518_1559'),
        ('checkout', '0016_auto_20210514_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_restaurant',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='restaurants.restaurant'),
        ),
    ]
